# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'postgres_exporter'
#     static_configs:
#       - targets: ['localhost:9187']
# scrape_configs:
#   - job_name: 'postgresql'
#     static_configs:
#       - targets: ['localhost:9187']

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']